language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.3.8
  - 2.5.3
  - 2.6.0
  - ruby-head

gemfile:
  - gemfiles/rails5_0_0.gemfile
  - gemfiles/rails5_0_1.gemfile
  - gemfiles/rails5_0_2.gemfile
  - gemfiles/rails5_0_3.gemfile
  - gemfiles/rails5_0_4.gemfile
  - gemfiles/rails5_0_5.gemfile
  - gemfiles/rails5_0_6.gemfile
  - gemfiles/rails5_0_7.gemfile
  - gemfiles/rails5_1_0.gemfile
  - gemfiles/rails5_1_1.gemfile
  - gemfiles/rails5_1_2.gemfile
  - gemfiles/rails5_1_3.gemfile
  - gemfiles/rails5_1_4.gemfile
  - gemfiles/rails5_1_5.gemfile
  - gemfiles/rails5_1_6.gemfile
  - gemfiles/rails5_2_0.gemfile
  - gemfiles/rails5_2_1.gemfile
  - gemfiles/rails5_2_2.gemfile
  - gemfiles/rails_edge.gemfile

env:
  - SETUP_TASK=turntable:db:reset BUILD_TASK=spec:all
  - SETUP_TASK=turntable:activerecord:setup BUILD_TASK=turntable:activerecord:test

services:
  - docker

before_install:
  - docker run -d --name turntable-katsubushi -p 11212:11212 katsubushi/katsubushi:latest -worker-id 1

before_script:
  - bundle exec rake $SETUP_TASK

script:
  - bundle exec rake $BUILD_TASK

matrix:
  exclude:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.8
  include:
    - rvm: 2.3.8
      gemfile: gemfiles/rails5_0_7.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails5_1_6.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails5_2_2.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
