test:
  clusters:
    user_cluster:
      algorithm: range_bsearch
      seq:
        user_seq:
          connection: user_seq
        barrage_seq:
          seq_type: :barrage
      shards:
        - connection: user_shard_1
          less_than: 20000
          slaves:
            - user_shard_1_1
        - connection: user_shard_2
          less_than: 40000
          slaves:
            - user_shard_2_1
        - connection: user_shard_1
          less_than: 60000
          slaves:
            - user_shard_1_1
        - connection: user_shard_2
          less_than: 80000
          slaves:
            - user_shard_2_1
        - connection: user_shard_3
          less_than: 10000000
          slaves:
            - user_shard_3_1
    event_cluster:
      algorithm: range_bsearch
      seq:
        user_seq:
          connection: user_seq
      shards:
        - connection: user_shard_4
          less_than: 20000
        - connection: user_shard_5
          less_than: 40000
        - connection: user_shard_4
          less_than: 60000
        - connection: user_shard_5
          less_than: 80000
        - connection: user_shard_6
          less_than: 10000000
    mod_cluster:
      algorithm: modulo
      seq:
        user_seq:
          connection: user_seq
      shards:
        - connection: user_shard_1
        - connection: user_shard_2
        - connection: user_shard_3
    mysql_mod_cluster:
      algorithm: modulo
      seq:
        user_seq:
          seq_type: mysql
          connection: user_seq
      shards:
        - connection: user_shard_1
        - connection: user_shard_2
        - connection: user_shard_3
    hash_slot_cluster:
      algorithm: hash_slot
      seq:
        user_seq:
          seq_type: mysql
          connection: user_seq
      shards:
        - connection: user_shard_1
          less_than: 4096
        - connection: user_shard_2
          less_than: 8192
        - connection: user_shard_3
          less_than: 12288
        - connection: user_shard_4
          less_than: 16384
  raise_on_not_specified_shard_query: false
  raise_on_not_specified_shard_update: false
